# Generated by Django 2.2 on 2019-06-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('pub_date', models.DateField(verbose_name='publish date')),
            ],
        ),
    ]
