# Generated by Django 2.2 on 2019-06-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.ManyToManyField(to='main_app.Category'),
        ),
    ]
