# Generated by Django 2.2 on 2019-06-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_fulluserform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullUserForm',
        ),
    ]
