# Generated by Django 2.2 on 2019-06-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='url',
            new_name='URL',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='photo',
            field=models.ManyToManyField(to='main_app.Photo'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='site_name',
            field=models.CharField(max_length=100),
        ),
    ]
