# Generated by Django 2.2 on 2019-06-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='tech_stack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Tech_stack'),
            preserve_default=False,
        ),
    ]
